// src/config/itemConfig.js
 const qiuxie = {
       "DIY": [
    { label: "科四黑白", value: 345 },
    { label: "科四橙红色", value: 346 },
    { label: "科四青绿色", value: 347 },
    { label: "字母哥3红色涂鸦", value: 348 },
    { label: "科比11暗金色", value: 349 },
    { label: "PG5橙白色", value: 350 },
    { label: "科四棉花糖", value: 351 },
    { label: "科比11粉蓝", value: 352 },
    { label: "KD11橙白色", value: 353 },
    { label: "欧文1红绿色", value: 354 },
    { label: "匡威BB AllStar低帮紫绿色", value: 355 },
    { label: "科四紫粉绿配色", value: 356 },
    { label: "库里2低帮全明星", value: 357 },
    { label: "库里4淡紫色", value: 358 },
    { label: "科四龙年", value: 359 },
    { label: "哈登8绿色", value: 360 },
    { label: "库里9棕红色", value: 361 },
    { label: "科四淡红粉蓝配色", value: 362 },
    { label: "KD11粉蓝色", value: 363 },
    { label: "科四粉绿黄配色", value: 364 },
    { label: "科四小丑粉鞋带配色", value: 365 },
    { label: "科四仿JA1", value: 366 },
    { label: "欧文1白色红色标", value: 367 },
    { label: "欧文8白蓝色", value: 368 },
    { label: "欧文1白色蓝标", value: 369 },
    { label: "欧文1紫色", value: 370 },
    { label: "PG6白灰蓝配色", value: 371 },
    { label: "欧文8蓝黑配色", value: 372 },
    { label: "欧文8黑白色", value: 373 },
    { label: "LUKA1白色", value: 374 },
    { label: "Why Not5沙漠配色", value: 375 },
    { label: "PG6红蓝色", value: 376 },
    { label: "匡威BB AllStar低帮黑绿配色", value: 377 },
    { label: "匡威BB AllStar低帮橙黄色", value: 378 },
    { label: "LUKA1梅红色", value: 379 },
    { label: "空军一号淡蓝色", value: 380 },
    { label: "欧文5深蓝色", value: 381 },
    { label: "匡威BB AllStar低帮棕红色", value: 382 },
    { label: "KD16PE深紫色", value: 383 },
    { label: "科四黄白蓝配色", value: 384 },
    { label: "Zion1棕红色", value: 385 },
    { label: "欧文5白金", value: 386 },
    { label: "欧文8中国年", value: 387 },
    { label: "欧文5UFO", value: 388 },
    { label: "欧文5蓝橙", value: 389 },
    { label: "欧文5紫罗兰", value: 390 },
    { label: "欧文5米黄色", value: 391 },
    { label: "欧文5白橙配color", value: 392 },
    { label: "欧文5黑灰color", value: 393 },
    { label: "科比11龙年", value: 394 },
    { label: "库里7橙红颜色", value: 395 },
    { label: "AJ36黄绿色", value: 396 },
    { label: "空军一号黑红颜色", value: 397 },
    { label: "欧文1黄绿色", value: 398 },
    { label: "科比11大师之路", value: 399 },
    { label: "欧文8红蓝颜色", value: 400 },
    { label: "欧文8俄勒冈颜色", value: 401 },
    { label: "AJ36黄绿橙颜色", value: 402 },
    // 科比X
    { label: "科比X 独立日", value: 403 },
    { label: "科比X 开赛夜", value: 404 },
    { label: "科比X 刺客粉", value: 405 },
    { label: "科比X 黄", value: 406 },
    { label: "科比X 青蜂侠", value: 407 },
    { label: "科比X 紫罗兰", value: 408 },
    { label: "科比X 红蓝", value: 409 },
    { label: "科比X 全明星", value: 410 },
    { label: "科比X 紫", value: 411 },

    // 科比11low
    { label: "科比11low 全明星", value: 412 },
    { label: "科比11low 蓝渐变", value: 413 },
    { label: "科比11low 黑灰红", value: 414 },
    { label: "科比11low 橘白", value: 415 },
    { label: "科比11low 德罗赞", value: 416 },
    { label: "科比11low 李小龙", value: 417 },
    { label: "科比11low 黑金", value: 418 },
    { label: "科比11low 紫黑", value: 419 },
    { label: "科比11low 小丑", value: 420 },
    { label: "科比11low 白生胶", value: 421 },
    { label: "科比11low 粉绿", value: 422 },

    // 科比4
    { label: "科比4 白金", value: 423 },
    { label: "科比4 北卡蓝", value: 424 },
    { label: "科比4 白紫", value: 425 },
    { label: "科比4 黄", value: 426 },
    { label: "科比4 黄白黑", value: 427 },

    // 科比AD黑人月
    { label: "科比AD黑人月", value: 428 },

    // 科比1
    { label: "科比1 黑紫", value: 429 },
    { label: "科比1 灰蓝", value: 430 },

    // 莫兰特2
    { label: "莫兰特2 蓝", value: 431 },
    { label: "莫兰特2 黑红", value: 432 },
    { label: "莫兰特2 白紫", value: 433 },
    { label: "莫兰特2 绿粉", value: 434 },

    // Lbj
    { label: "Lbj22 紫绿", value: 435 },

    // JT2
    { label: "JT2 白紫", value: 436 },

    // 安东尼pe
    { label: "安东尼pe 36 黑红", value: 437 },
    { label: "安东尼pe 36 紫外线", value: 438 },
    { label: "安东尼pe 36 红蓝", value: 439 },
    { label: "安东尼pe 36 蓝粉", value: 440 },
    { label: "安东尼pe 35 彩", value: 441 },
    { label: "安东尼pe 37 军绿", value: 442 },
    { label: "安东尼pe 33 黑红", value: 443 },

    // Dame5
    { label: "Dame5 黑红", value: 444 },
    { label: "Dame5 黄黑", value: 445 },
    { label: "Dame5 黑白", value: 446 },

    // Dame6
    { label: "Dame6 红黑", value: 447 },
    { label: "Dame6 蓝红", value: 448 },
    { label: "Dame6 黑橘", value: 449 },

    // BYW X
    { label: "BYW X 黑彩", value: 450 },
    { label: "BYW X 尼克杨", value: 451 },
    { label: "BYW X 紫金", value: 452 },

    // 哈登8
    { label: "哈登8 黑白", value: 453 },
    { label: "哈登8 黑粉", value: 454 },

    // AE低
    { label: "AE低 黑粉", value: 455 },

    // Sel2
    { label: "Sel2 黄红", value: 456 },
    { label: "Sel2 橘绿", value: 457 },
    { label: "Sel2 粉", value: 458 },

    // Zone boost
    { label: "Zone boost 拼色", value: 459 },

    // 哈登3
    { label: "哈登3 德鲁联赛", value: 460 },
    { label: "哈登3 奥利奥", value: 461 },
    { label: "哈登3 灰虎纹", value: 462 },
    { label: "哈登3 黑粉", value: 463 },

    // Puma
    { label: "Puma 橘黄", value: 464 },
    { label: "Puma 南海岸", value: 465 },
    { label: "Puma 黑白", value: 466 },

    // PG2
    { label: "PG2 灰蓝", value: 467 },
    { label: "PG2 南海岸", value: 468 },
    { label: "PG2 雷霆", value: 469 },
    { label: "PG2 白", value: 470 },

    // PG2.5
    { label: "PG2.5 黄黑", value: 471 },
    { label: "PG2.5 宝蓝", value: 472 },
    { label: "PG2.5 白兰", value: 473 },

    // PG5
    { label: "PG5 黑白", value: 474 },
    { label: "PG5 蓝粉", value: 475 },
    { label: "PG6棉花糖", value: 476 },
    { label: "PG5 黑金", value: 477 },
    { label: "PG5 红蓝", value: 478 },

    // Kd12
    { label: "Kd12 黑白", value: 479 },

    // Kd13
    { label: "Kd13 白黑", value: 480 },
    { label: "Kd13 黑彩", value: 481 }
],
  "球鞋阿迪": [
    { label: "LILLARD3 全红", value: 62 },
    { label: "LILLARD3 全红-可编辑", value: 63 },
    { label: "LILLARD3 全明星", value: 64 },
    { label: "LILLARD3 黑色", value: 65 },
    { label: "LILLARD3 绝版", value: 66 },
    { label: "LILLARD3 比赛", value: 67 },
    { label: "LILLARD3 默认", value: 68 },
    { label: "LILLARD3 淡黄色", value: 69 },
    { label: "BYW X默认2038", value: 70 },
    { label: "BYW X比赛2038", value: 71 },
    { label: "BYW X第一代", value: 72 },
    { label: "BYW X默认 2039", value: 73 },
    { label: "BYW X比赛2039", value: 74 },
    { label: "哈登3默认", value: 75 },
    { label: "哈登3比赛", value: 76 },
    { label: "哈登3一代", value: 77 },
    { label: "哈登3二代", value: 78 },
    { label: "利拉德5默认", value: 79 },
    { label: "利拉德5比赛", value: 80 },
    { label: "利拉德5浅蓝色", value: 81 },
    { label: "利拉德5石灰绿", value: 82 },
    { label: "罗斯9默认", value: 83 },
    { label: "罗斯9比赛", value: 84 },
    { label: "罗斯9一代", value: 85 },
    { label: "罗斯9二代", value: 86 },
    { label: "罗斯9三代", value: 87 }
  ],
  "球鞋AIR-乔丹": [
    { label: "AJ1全明星17", value: 88 },
    { label: "AJ1全明星3", value: 89 },
    { label: "AJ1全白色", value: 90 },
    { label: "AJ1默认", value: 91 },
    { label: "AJ1比赛", value: 92 },
    { label: "AJ1绿色", value: 93 },
    { label: "AJ1乔丹主场-可编辑", value: 94 },
    { label: "AJ1湖人队", value: 95 },
    { label: "AJ1金属绿", value: 96 },
    { label: "AJ1金属红", value: 97 },
    { label: "AJ1海军蓝", value: 98 },
    { label: "AJ1NC", value: 99 },
    { label: "AJ1初级编辑", value: 100 },
    { label: "AJ1反向", value: 101 },
    { label: "AJ1新秀", value: 102 },
    { label: "AJ1皇家蓝", value: 103 },
    { label: "AJ1破碎的篮板", value: 104 },
    { label: "AJ1涡轮绿", value: 105 },
    { label: "AJ1小麦", value: 106 },
    { label: "AJ1白板", value: 107 },
    { label: "AJ1沃尔夫格雷", value: 108 },
    { label: "AJ1黄脚趾", value: 109 },
    { label: "AJ1 jtblue", value: 110 },
    { label: "AJ5纯红", value: 111 },
    { label: "AJ5纯白", value: 112 },
    { label: "AJ5麂皮蓝", value: 113 },
    { label: "AJ5麂皮蓝-红", value: 114 },
    { label: "AJ5水泥", value: 115 },
    { label: "AJ5默认", value: 116 },
    { label: "AJ5朋友", value: 117 },
    { label: "AJ5比赛", value: 118 },
    { label: "AJ5兀立岩石", value: 119 },
    { label: "AJ5隐身", value: 120 },
    { label: "AJ5晚霞", value: 121 },
    { label: "AJ5标记2", value: 122 },
    { label: "AJ5东京", value: 123 },
    { label: "AJ5葡萄紫", value: 124 },
    { label: "AJ5葡萄紫-可编辑", value: 125 },
    { label: "AJ5兰尼", value: 126 },
    { label: "AJ5金属", value: 127 },
    { label: "AJ5奖杯", value: 128 },
    { label: "AJ5金属白", value: 129 },
    { label: "AJ32默认", value: 130 },
    { label: "AJ32比赛", value: 131 },
    { label: "AJ32初级-可编辑", value: 132 },
    { label: "AJ32俄罗斯", value: 133 },
    { label: "AJ32白色-可编辑", value: 134 }
  ],
  "Nike AIR系列": [
    { label: "PRO金", value: 206 },
    { label: "PRO黑白", value: 207 },
    { label: "PRO黑", value: 208 },
    { label: "PRO南瓜", value: 209 },
    { label: "PRO白银", value: 210 },
    { label: "PRO紫色", value: 211 },
    { label: "PRO青色", value: 212 },
    { label: "PRO白银2", value: 213 },
    { label: "PRO丑色", value: 214 },
    { label: "PRO红色", value: 215 },
    { label: "MAX白色", value: 216 },
    { label: "MAX灰色", value: 217 },
    { label: "MAX深蓝", value: 218 },
    { label: "MAX白色2", value: 219 },
    { label: "MORE红黑", value: 220 },
    { label: "MORE蓝白", value: 221 },
    { label: "MORE紫金", value: 222 },
    { label: "MORE黑色", value: 223 },
    { label: "MORE紫白", value: 224 },
    { label: "MORE白黑", value: 225 },
    { label: "MORE金紫", value: 226 }
  ],
  "JORDAN系列": [
    { label: "乔丹2白色", value: 227 },
    { label: "乔丹2黑色", value: 228 },
    { label: "乔丹2蓝色", value: 229 },
    { label: "乔丹2红色", value: 230 },
    { label: "乔丹2白紫", value: 231 },
    { label: "乔丹2白蓝", value: 232 },
    { label: "乔丹2绿色", value: 233 },
    { label: "乔丹2黄色", value: 234 },
    { label: "乔丹3黑色", value: 235 },
    { label: "乔丹3金色", value: 236 },
    { label: "乔丹3黑蓝", value: 237 },
    { label: "乔丹3黑白", value: 238 },
    { label: "乔丹3蓝色", value: 239 },
    { label: "乔丹3白色", value: 240 },
    { label: "乔丹3黑红", value: 241 },
    { label: "乔丹4黑蓝", value: 242 },
    { label: "乔丹4白红", value: 243 },
    { label: "乔丹4黑色", value: 244 },
    { label: "乔丹4红色", value: 245 },
    { label: "乔丹6白色", value: 246 },
    { label: "乔丹6深蓝色", value: 247 },
    { label: "乔丹6绿色", value: 248 },
    { label: "乔丹6白红", value: 249 },
    { label: "乔丹6镀金", value: 250 },
    { label: "乔丹7镀金", value: 251 },
    { label: "乔丹7黑色", value: 252 },
    { label: "乔丹11镀金", value: 253 },
    { label: "乔丹11黑红", value: 254 },
    { label: "乔丹11北卡蓝", value: 255 },
    { label: "乔丹11熊猫", value: 256 },
    { label: "乔丹11紫色", value: 257 },
    { label: "乔丹11白金", value: 258 },
    { label: "乔丹12黑白", value: 259 },
    { label: "乔丹12纯白", value: 260 },
    { label: "乔丹12黑红", value: 261 },
    { label: "乔丹12红白", value: 262 },
    { label: "乔丹12镀金", value: 263 },
    { label: "乔丹32黑红", value: 264 },
    { label: "乔丹32乳腺癌", value: 265 },
    { label: "乔丹32蓝色", value: 266 },
    { label: "乔丹35黑红", value: 267 },
    { label: "乔丹35彩色", value: 268 },
    { label: "乔丹37白色", value: 269 },
    { label: "乔丹37迷彩绿", value: 270 },
    { label: "CP3黑蓝", value: 271 },
    { label: "CP3红色", value: 272 },
    { label: "CP3黑红", value: 273 },
    { label: "CP3白红", value: 274 },
    { label: "LUKA1红色", value: 275 },
    { label: "ZERO0.5", value: 276 },
    { label: "ZION1黑白", value: 277 },
    { label: "ZION1灰粉", value: 278 }
  ],
  "Adidas系列": [
    { label: "CRAZY8蓝色", value: 279 },
    { label: "CRAZY8白色", value: 280 },
    { label: "CRAZY8黑白", value: 281 },
    { label: "DAME2白色", value: 282 },
    { label: "DAME7银色", value: 283 },
    { label: "DAME7粉色", value: 285 },
    { label: "ADIDAS3蓝色", value: 286 },
    { label: "ISSUE1PE红蓝", value: 288 },
    { label: "ISSUE1黑色", value: 289 },
    { label: "ROSE10白色", value: 290 },
    { label: "ADIDAS ROSE", value: 291 },
    { label: "HARDEN1黑黄", value: 292 },
    { label: "HARDEN1黑白", value: 293 },
    { label: "HARDEN5青蓝", value: 294 },
    { label: "HARDEN6蓝绿", value: 295 },
    { label: "L3V3L白蓝", value: 296 },
    { label: "L3V3L蓝色", value: 297 },
    { label: "TRAE YOUNG1", value: 298 },
    { label: "T-MAC3绿色", value: 299 },
    { label: "T-MAC3黑色", value: 300 },
    { label: "T-MAC3橙色", value: 301 },
    { label: "T-MAC3黄色", value: 302 },
    { label: "T-MAC3蓝色", value: 303 },
    { label: "T-MAC3红色", value: 304 }
  ],
  "Nike系列": [
    { label: "KYRIE1红色", value: 306 },
    { label: "KYRIE5黄色", value: 307 },
    { label: "KYRIE5浅蓝", value: 308 },
    { label: "KYRIE5灰绿", value: 309 },
    { label: "KYRIE5深蓝", value: 310 },
    { label: "KYRIE5白色", value: 311 },
    { label: "KYRIE5土色", value: 312 },
    { label: "KYRIE5彩色", value: 315 },
    { label: "KYRIE8红色", value: 316 },
    { label: "LeBron黑白", value: 317 },
    { label: "LeBron白红", value: 318 },
    { label: "LeBron白黑", value: 319 },
    { label: "LeBron黑色", value: 320 },
    { label: "LeBron美国队", value: 321 },
    { label: "LeBronX金色", value: 322 },
    { label: "LeBronX红色", value: 323 },
    { label: "LeBronX白色", value: 324 },
    { label: "LeBron15粉色", value: 325 },
    { label: "LeBron13黑色", value: 328 },
    { label: "PG2黑蓝", value: 329 },
    { label: "PG2彩色", value: 330 },
    { label: "PG2灰色", value: 331 },
    { label: "PG2.5橙色", value: 333 },
    { label: "PG2.5黑色", value: 334 },
    { label: "PG5白色", value: 335 },
    { label: "PG6青色", value: 336 },
    { label: "PG6灰红", value: 337 },
    { label: "FREAK3灰", value: 338 }
  ],
  "Under Armour系列": [
    { label: "curry2蓝", value: 339 },
    { label: "curry4low黑色", value: 340 },
    { label: "curry9黑黄", value: 341 },
    { label: "curry9球队色", value: 342 },
    { label: "HAVOC3粉黑", value: 343 },
    { label: "EMBIID1黑灰", value: 344 }
  ],
  "科比四-科比11系列": [
    { label: "科比4黑色", value: 188 },
    { label: "科比4布克紫", value: 189 },
    { label: "科比4橙色", value: 190 },
    { label: "科比4行乐白", value: 191 },
    { label: "科比行乐黑", value: 192 },
    { label: "科比4选秀日", value: 193 },
    { label: "科比11白紫", value: 194 },
    { label: "科比11黑红", value: 195 },
    { label: "科比11橙黄", value: 196 },
    { label: "科比11黑色", value: 197 },
    { label: "科比11青蜂侠", value: 198 },
    { label: "科比11白蓝", value: 199 },
    { label: "科比11黄紫", value: 200 },
    { label: "科比11深蓝", value: 201 },
    { label: "科比11绿紫", value: 202 },
    { label: "科比11橙色", value: 203 },
    { label: "科比11红", value: 204 },
    { label: "科比11红蓝", value: 205 }
  ],
  "科比AD系列": [
    { label: "黑白色", value: 1 },
    { label: "默认", value: 2 },
    { label: "德罗赞之家", value: 3 },
    { label: "德罗赞之家红色", value: 4 },
    { label: "比赛", value: 5 },
    { label: "iggy家庭配色", value: 6 },
    { label: "iggy黑色", value: 7 },
    { label: "iggy蓝色家庭配色", value: 8 },
    { label: "金黑人月", value: 9 },
    { label: "深蓝色", value: 10 },
    { label: "初级编辑", value: 11 },
    { label: "中级编辑", value: 12 },
    { label: "高级编辑", value: 13 },
    { label: "次要编辑", value: 14 },
    { label: "扇区编辑", value: 15 },
    { label: "教授编辑", value: 16 },
    { label: "复杂编辑", value: 17 },
    { label: "终极编辑", value: 18 },
    { label: "托马斯韦配色", value: 19 },
    { label: "托马斯韦配色", value: 20 },
    { label: "托马斯韦绿色配色", value: 21 },
    { label: "托马斯韦家庭配色", value: 22 },
    { label: "大学配色", value: 23 },
    { label: "白银配色", value: 24 },
    { label: "欧文5", value: 25 },
    { label: "库里1", value: 26 }
  ],
  "球鞋PG KD": [
    { label: "PG2.5默认", value: 27 },
    { label: "PG2.5游戏日", value: 28 },
    { label: "PG2.5第一代", value: 29 },
    { label: "PG2.5球员版2", value: 30 },
    { label: "KD11默认", value: 31 },
    { label: "KD11游戏日", value: 32 },
    { label: "KD11球员版1", value: 33 },
    { label: "KD11尼龙", value: 34 }
  ],
  "球鞋詹姆斯16": [
    { label: "黑郁金香", value: 35 },
    { label: "美元", value: 36 },
    { label: "骑兵", value: 37 },
    { label: "比赛", value: 38 },
    { label: "绿黑色", value: 39 },
    { label: "灰熊", value: 40 },
    { label: "灰熊2", value: 41 },
    { label: "老鹰", value: 42 },
    { label: "黄蜂", value: 43 },
    { label: "尼克斯", value: 44 },
    { label: "湖人", value: 45 },
    { label: "湖人2", value: 46 },
    { label: "勒布朗1", value: 47 },
    { label: "勒布朗2", value: 48 },
    { label: "勒布朗3", value: 49 },
    { label: "独行侠", value: 50 },
    { label: "独行侠2", value: 51 },
    { label: "篮网1", value: 52 },
    { label: "篮网2", value: 53 },
    { label: "魔术", value: 54 },
    { label: "红蓝色", value: 55 },
    { label: "红白色", value: 56 },
    { label: "太阳队1", value: 57 },
    { label: "太阳队2", value: 58 },
    { label: "勇士", value: 59 },
    { label: "黄色", value: 60 },
    { label: "默认", value: 61 }
  ],
  "球鞋AIR-乔丹31": [
    { label: "AJ31全黑色", value: 135 },
    { label: "AJ31全明星", value: 136 },
    { label: "AJ31全白色", value: 137 },
    { label: "AJ31双色黑蓝", value: 138 },
    { label: "AJ31双色黑色", value: 139 },
    { label: "AJ31双洋蓝色", value: 140 },
    { label: "AJ31双色白色", value: 141 },
    { label: "AJ31蓝色双色", value: 142 },
    { label: "AJ31黑猫", value: 143 },
    { label: "AJ31公牛色", value: 144 },
    { label: "AJ31管家黑", value: 145 },
    { label: "AJ31布莱恩", value: 146 },
    { label: "AJ31布莱特红", value: 147 },
    { label: "AJ31管家主场", value: 148 },
    { label: "AJ31中国新年特别版", value: 149 },
    { label: "AJ31圣诞节", value: 150 },
    { label: "AJ31康利客场配色", value: 151 },
    { label: "AJ31康利黑紫色", value: 152 },
    { label: "AJ31康利主场配色", value: 153 },
    { label: "AJ31康利粉蓝色", value: 154 },
    { label: "AJ31康利黄色", value: 155 },
    { label: "AJ31克罗地亚", value: 156 },
    { label: "AJ31克罗地亚主场", value: 157 },
    { label: "AJ31默认", value: 158 },
    { label: "AJ31椭圆黑色", value: 159 },
    { label: "AJ31椭圆配色", value: 160 },
    { label: "AJ31椭圆蓝黄色", value: 161 },
    { label: "AJ31乔治城", value: 162 },
    { label: "AJ31万圣节", value: 163 },
    { label: "AJ31黄蜂灰色", value: 164 },
    { label: "AJ31灯草黑", value: 165 },
    { label: "AJ31白色", value: 166 },
    { label: "AJ31卡威语灰色", value: 167 },
    { label: "AJ31卡威语黑色", value: 168 },
    { label: "AJ31卡威语深灰色色", value: 169 },
    { label: "AJ31卡威语白色", value: 170 },
    { label: "AJ31迈克尔基德主场", value: 171 },
    { label: "AJ31莱昂纳多", value: 172 },
    { label: "AJ31储物", value: 173 },
    { label: "AJ31梦露黑色", value: 174 },
    { label: "AJ31梦露白色", value: 175 },
    { label: "AJ31粉红色", value: 176 },
    { label: "AJ31红黑相间", value: 177 },
    { label: "AJ31里约", value: 178 },
    { label: "AJ31破碎的篮板", value: 179 },
    { label: "AJ31太空干扰", value: 180 },
    { label: "AJ31男式", value: 181 },
    { label: "AJ31美国队球鞋", value: 182 },
    { label: "AJ31美国队球鞋2", value: 183 },
    { label: "AJ31威少主场", value: 184 },
    { label: "AJ31私人红", value: 185 },
    { label: "AJ31比赛", value: 186 },
    { label: "AJ31棕灰色", value: 187 }
  ]
};
